### ISSUE TITLE
关于日志打印

### ISSUE THREAD

**Issue by hegelsu** [ckrgithub/FlexItemDecoration#2]
正式环境会打这么多Log么？
drawHorizontal: !noDrawHeaderDivider:0,adapterPosition:0
getItemOffsets: itemPosition:14

**Comment by ckrgithub** [comment]
不好意思，这么久才回复。log的打印已经修正了

**Comment by ckrgithub** [comment]
已经解决了。真不好意思这么久才回复

2018-02-17 23:10 GMT+08:00 hegelsu <notifications@github.com>:

**Comment by hegelsu** [comment]
好的，辛苦了。
